### ISSUE TITLE
Вопросы по РК

### ISSUE THREAD

**Issue by TonitaN** [bmstu-iu9/TerminatorBattle2021#1]
Здесь можно задавать вопросы. Дублирую вопрос Даниэлы:

> На первой строке задается список допустимых переменных, входящих в конструктор? Получается, в случае test_loop1 вот на таком тесте должна выйти ошибка из-за переменной `z`?
```
[x,y]
g(y,z) -> f(z)
f(x) -> g(h(z), z)
```

*Ответ:* это не ошибка. Если терм не входит в список переменных, но не требует аргументов, это константа, как в данном случае `z`. Может быть и другая ситуация --- переменная с именем, состоящим больше, чем из одной буквы.

**Comment by MuonSevasch** [comment]
А какой именно Вы используете рефал и можно ли узнать какой компилятор используется для сборки?

**Comment by TonitaN** [comment]
5-lambda. Устанавливать специально не надо, есть же докерфайл.

**Comment by ZhukDmitryOlegovich** [comment]
А можно формально правило записи тестов? 

Я так понял в первой не пустой строке в квадратных скобках однобуквенные названия переменных в нижнем регистре

В каждой последующей не пустой строке - правило из трех частей: 
1) либо функция (названием - многобуквенное (/WFMA/test_fuma1.trs)? в нижнем регистре?), либо переменная (из указанных выше), либо константа (одна буква в большом регистре, но /Loop/test_loop3.trs 3 строка некая g) + не пустая последовательность + правильная скобочная последовательность / расстановка запятых / кол-во аргументов у функций
2) ->
3) тоже что и в (1)

**Comment by TonitaN** [comment]
Вообще, имена переменных и конструкторов --- в регулярке ([A-z])+. То есть могут быть и многобуквенные, и от регистра не зависят. При этом переменные, перечисленные в списке, не обязаны входить в правила.

**Comment by TonitaN** [comment]
Там в скрипте таймаут короткий выставлен. Поменяйте так, как вам удобно.

**Comment by ZhukDmitryOlegovich** [comment]
А подскажите как правильно в докер запускать? Сделал `sudo dockerd`, но как именно как `./run_docker.sh` не могу понять
![image](https://user-images.githubusercontent.com/93006259/146149652-c574b89a-2305-4ee0-85ee-1d7747d50914.png)

**Comment by TonitaN** [comment]
`sudo ./run_docker.sh` не работает?

**Comment by sir-timio** [comment]
Не находит ./test_gen и ./test_check

**Comment by TonitaN** [comment]
Вы запускали скрипт `run_test` вне докера? Не найдет. Запускайте докер скрипт, он вызовет `run_test` уже в правильном окружении.

**Comment by sir-timio** [comment]
спасибо

**Comment by ZhukDmitryOlegovich** [comment]
Ой, вроде как-то куда-то надо решения свое периодически публиковать - это в ветку этого репозитория делать или рано?

**Comment by ZhukDmitryOlegovich** [comment]
![image](https://user-images.githubusercontent.com/93006259/146160741-208508c4-7b34-4399-bf02-67018c60f5a0.png)
![image](https://user-images.githubusercontent.com/93006259/146160789-620f2a7b-39c5-49a9-99d4-16fbdcfdc5f2.png)
а в 57 тесте ошибочка - скобки нету закрывающей, а пишет что не синтаксическая ошибка

Можно доп балл?)

**Comment by ZhukDmitryOlegovich** [comment]
и в 74 - нет блока с объявлением переменных - это надо поддерживать или ошибка в тесте?

**Comment by TonitaN** [comment]
Да, всё верно, 74 и 57 - по допбаллу всем нашедшим ))) У вас с Пашей уже 3,5.

**Comment by TonitaN** [comment]
> Ой, вроде как-то куда-то надо решения свое периодически публиковать - это в ветку этого репозитория делать или рано?

Вообще ссылку на репозиторий надо, но всё равно никто не прислал почти, поэтому можно и не высылать пока. Мы продлили дедлайн до часу ночи, кстати.

**Comment by TonitaN** [comment]
Файл `test_check` обновлён.

**Comment by MuonSevasch** [comment]
А в каком формате присылать тесты с ответами, если мы сумели их разобрать?

**Comment by TonitaN** [comment]
В каком считаете нужным.

**Comment by MuonSevasch** [comment]
Отправили

**Comment by TonitaN** [comment]
Тест 75 тоже снимается ) Жук +1

**Comment by TonitaN** [comment]
45 снят. Дьячек +1. Похоже, при переносе часть хешей генерировалась и читалась разными формулами. Проверю, как только приеду в Переславль. Хотя я надеюсь, что это всего лишь ошибка копипэйста, и их не так много там.

**Comment by TonitaN** [comment]
Вроде, грубых ляпов не видно. Значит, всё-таки не кодировка, а отдельные вердикты косячили.

**Comment by ZhukDmitryOlegovich** [comment]
![image](https://user-images.githubusercontent.com/93006259/146226831-9a29b514-d7ff-49ba-a1b3-f93743681680.png)
в 40 тесте ошибка - можно накапливать H: 
|  | | | 
| --: | -- | -- |
| `E(H(B(G(B(A(B(J(B(G(B(G(D(x)))))))))))))_` |  `->` | `E(H(B(G(B(A(B(B(B(G(B(G(D(x)))))))))))))`| 
| `H(E(H(B(G(B(A(B(J(B(G(B(G(D(x))))))))))))))` |  `<-` | `E(H(B(G(B(A(B(B(B(G(B(G(D(x)))))))))))))` |

**Comment by ZhukDmitryOlegovich** [comment]
![image](https://user-images.githubusercontent.com/93006259/146238403-b10e5c01-0405-430e-8236-342fa69b52c8.png)
в 77 тесте ошибка - можно сделать `f(x,x,x,x) -> f(x,x,x,x)`

**Comment by TonitaN** [comment]
Может, и глюк с незавершайками. Предыдущую точно помню как зацикленную. Приеду, проверю и все глючные тесты объявлю халявными по 0,5 баллов.

**Comment by Perpure** [comment]
![image](https://user-images.githubusercontent.com/24734435/146241527-22d4f8a4-23d3-4336-a639-afcc362ae049.png)

**Comment by Danya-Is** [comment]
Test19 { = 
'-67932147204790855_THREE------------------------------------'
[x,y]
a(x,u(y)) -> u(a(x,y))
a(x,Z) -> x
m(x,u(y)) -> a(m(x,y),x)
m(x,Z) -> Z
; }
А почему этот тест не входит в категорию лексикографического порядка, если в соответсвии с правилами и из предположения, что m > a > u получается что все левые части больше своих правых?

**Comment by Danya-Is** [comment]
И правильно ли я понимаю, что в все константы считаются равными и также константа будет равна любой переменной?

**Comment by ZhukDmitryOlegovich** [comment]
всм все константы равны?

**Comment by Perpure** [comment]
По-моему еще в 37 и 38 ошибки.
вот 37 например совсем легкий:
[x]
A(D(x)) -> B(D(x))
C(x) -> B(x)
B(x) -> I(x)
I(x) -> A(x)
ad->bd->id->ad

**Comment by Danya-Is** [comment]
> всм все константы равны?

в плане лексикографического сравнения, например f(H) = f(C) = f(а), где а это переменная а остальное константы

**Comment by TonitaN** [comment]
Жук, вы 🔥🔥🔥!!!

**Comment by TonitaN** [comment]
Через три часа всем напишу

**Comment by TonitaN** [comment]
Таки да, генератор хешей иногда генерил неправильные witness-файлы для отрицательных тестов, отсюда и лажа. Как и обещала, каждый лагающий в первом варианте тест будет засчитан как 0,5 независимо от успешности его прохождения всем командам.
То есть тесты номер 75, 57, 74, 45, 40, 77, 37, 38 считаются халявой, по 4 балла каждой команде. Сейчас я перевыложу базу тестов, где они будут уже определяться правильно.

**Comment by TonitaN** [comment]
С 19 нет ошибки. К лексикографическим по типажу относились только тесты, где лексикографический порядок был тупо на множествах имён конструкторов, без учёта структуры (т.е. упорядочение >_lo с первых слайдов - это более сильный порядок, чем тот, который подразумевался на группе из 35 тестов).

**Comment by TonitaN** [comment]
По переменным - не совсем. Все переменные равны, а константы также имеют веса. При этом переменная считается не меньше *любой* константы, но и не больше.

**Comment by TonitaN** [comment]
Завтра (уже сегодня) посчитаю предварительные баллы за РК без срезов и начну делать срезы, кроме бесконечности.
